brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
namesrvAddr = rocketmq-namesrv:9876
brokerIP1 = 127.0.0.1
autoCreateTopicEnable = true
storePathRootDir = /home/rocketmq/store
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH
listenPort = 10911